### ISSUE TITLE
kafka.log.partition.size metric

### ISSUE THREAD

**Issue by mthoretton** [DataDog/kafka-kit#267]
Hello,

I was looking in the doc, issues and internet, no way to find how to push `kafka.log.partition.size` metric. It's not part of the default of the default metrics https://docs.datadoghq.com/integrations/kafka/.

Do I need a custom conf or a custom check? thanks!

**Comment by mthoretton** [comment]
So, in order to collect it, you need a custom conf (which is actually based on JMX). See https://github.com/DataDog/integrations-core/blob/master/kafka/datadog_checks/kafka/data/conf.yaml.example

This is the conf to add. The order of the parameters in `bean_regex` matters! I was able to debug thanks to https://docs.datadoghq.com/integrations/faq/troubleshooting-jmx-integrations/?tab=agentv6 .

```
init_config:
  is_jmx: true
  collect_default_metrics: true
  conf:
    ...
    - include:
        domain: 'kafka.log'
        bean_regex: 'kafka\.log:type=Log,name=Size,topic=(.*?),partition=(.*?)(?:,|$)'
        tags:
          topic: $1
          partition: $2
        attribute:
          Value:
            alias: kafka.log.partition.size
            metric_type: gauge
```

By adding that we may hit the default 350 JMX metrics limit though.

Feel free to add that to the doc (I could also create a PR) or close this issue.
